### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by GeceGibi** [relateddigital/relateddigital-flutter#4]
Need to complete to null safety migration. 
https://dart.dev/null-safety/migration-guide

After Dart 3 upgrade, Unsound Null Safety packages will be useless.
https://medium.com/dartlang/the-road-to-dart-3-afdd580fbefa

**Comment by cicimen** [comment]
We started converting the SDK to null-safe in a different branch(https://github.com/relateddigital/relateddigital-flutter/tree/master-combined). Null safe version of SDK will be available in a few weeks.

**Comment by GeceGibi** [comment]
Any changes ? @cicimen

**Comment by cicimen** [comment]
@GeceGibi we published a new version (0.5.4) which is null-safe.
